### ISSUE TITLE
Cemu window is not visible when Budford is launched via command line

### ISSUE THREAD

**Issue by Bartegu** [SteveLeafo/Budford#10]
### Expected Behavior
Cemu window should be visible in the taskbar and on the screen.
### Actual Behavior
I use Budford to launch different games via steam Big Picture. However it looks like i've found a bug when Budford is launched via command line - `Path/to/Budford.exe -f -g /path/to/rdx` . Sometimes the cemu window doesn't appear at all and there is no window available in the Windows taskbar. I can find Cemu.exe process in task manager and hear game sounds, so it looks like the cemu has properly started, but the game is not visible on any desktop and any screen. The only way to fix this issue is to reboot PC.
### Steps to reproduce
I haven't been able to reproduce this problem. It happens randomly, and is fixed by restarting the PC. I've tested this behaviour on 1 display configuration and launched Budford via command line directly from CMD and from Steam BP shortcut.

**Comment by IceLancerSR** [comment]
shouldnt command be  budford.exe -g GAMENAME -f
-f -g gamename doesnt work for cemu

**Comment by Bartegu** [comment]
It doesn't make a difference for me. budford.exe -g GAMENAME -f (or event without -f flag) causes the same issue. Replacing /path/to/budford.exe with /path/to/cemu.exe makes it work just fine (even with -f -g gamename).

**Comment by IceLancerSR** [comment]
I just realized , why are u using -f -g at all?
All your cemu config are handled by Budford including per game screen size. U just need to pass  budford.exe GAMENAME

Some time ago i have wrote batch script to use it for cemu for portable purposes which can be used on any frontend. Same can be applied for budford as he is replacement for cemu.

@echo off
set "GAMENAME=U-King.rpx"
set "GAMEPATH=Roms\The Legend of Zelda Breath of the Wild [ALZP0101]\code\"
set "CEMUPATH=..\..\Emulators\Cemu\Budford\"
set "ROM=%~dp0%GAMEPATH%"
set HOME="%~dp0"
set "EMUROOT=%~dp0%CEMUPATH%"
cd %EMUROOT%
start "" /WAIT "%EMUROOT%Budford.exe" "%ROM%%GAMENAME%"
exit

start "" /WAIT is necesary for some frontends so they will go in inactive mod otherwise they might stay active in background. Code uses relative pathing and is very simple and portable. In front end u just add batch file as game ,thats it.
in case of CEMU last line would be:
start "" /WAIT "%EMUROOT%Cemu.exe" -g "%ROM%%GAMENAME%" -f

More detailed explanation can be found here:
http://forum.attractmode.org/index.php?topic=2042

**Comment by Bartegu** [comment]
Doesn't really make a difference - if I use command line to start game with Budford, the game is started in the background. Cemu.exe is visible only in task manager, and i can hear game audio, but there is nothing displayed on the screen. At this point I pretty much give up on Budford, looked like a cool app that i could use to setup few games for Steam BP, but in the end it's much easier to create few batch scripts that copy settings and run cemu.exe directly.

**Comment by IceLancerSR** [comment]
I dont know how can u have such problem. its working absolutely perfect here.
Maybe its your front end that is problem? what are u using to start game from Budford?

**Comment by Bartegu** [comment]
I'll give you a step by step how this issue occurs to me:
1. Open CMD
2. Change path to F:\Gry\Budford
3. Launch game with F:\Gry\Budford>Budford.exe "F:\Gry\cemu\Games\ZeldaBotW\code\U-King.rpx"

At this point game launches in background with no way to focus the window (there is no window in the taskbar) but i can hear the game sounds..

I've already tried launching it with flags -f -g the way you suggested before. Same thing also happens if i try to use steam BP.

Game launches just fine if i try to start it via Budford GUI. It also starts just fine if i try to run it from CMD using cemu.exe instead of budford.exe. Maybe I'm doing something wrong, but there is really no documentation for starting budford from command line - it was suggested on reddit to use it the same way as cemu.exe and that's what I'm doing.

**Comment by IceLancerSR** [comment]
>Budford.exe "e:\Igre\RetroPie\EmulationMix\Roms\Nintendo Wii U\Roms\The Legend of Zelda Breath of the Wild [ALZP0101]\code\U-King.rpx"
it works fine here man, budford starts minimized /hiden cemu window appears on top with game..

**Comment by Bartegu** [comment]
I've just tried CMD with admin rights - same thing. I've uninstalled Budford and cemu and installed newest Budford and downloaded cemu via budford. I've added games directory and checked that i can run each game via Budford UI - everything works. Now I've tried to run it via CMD (admin/no admin, with flags and without flags etc) or Steam BP - exact same thing as before, cemu starts as hidden window. I've even unplugged my TV from PC to exclude problems with external display, still no go. I've already run out of options here.

**Comment by IceLancerSR** [comment]
Wait u mentioned that there is no window in taskbar?
There should be two windows, budford and cemu in taskbar and u said now that u have dual monitors?
If there is no taskbar then one of windows have went to other monitor.If you hear sounds app cant be in memory alone, it means its active but something is messing it up on dual monitors. Unfortunately i do not have two on one pc to check it out. Yes u said u unplugged one but that doesnt mean much. If app is assigned to other monitor it will keep going there. Have u turned off multimonitor supp in windows? its "project" option on right side of clock in taskbar

**Comment by SteveLeafo** [comment]
OK - I have now been able to reproduce this issue.  

I am seeing the symptoms exactly as you described. I should have a fix in the next couple of hours.

Sorry it took me so long to reply - but I guess sometimes work gets priority.

**Comment by SteveLeafo** [comment]
Hi, thanks for raising this issue.

It has been fixed in 1.0.59 which is now available for download.

Sorry it took so long to fix.

Regards,
SteveLeafo

**Comment by Bartegu** [comment]
@SteveLeafo I can confirm that it has been fixed in 1.0.59, thanks a lot for taking your time and fixing this bug!

@IceLancerSR I also wanted to thank you for trying to help me and suggesting various workarounds :)
