### ISSUE TITLE
Mouse Right click for giro not working

### ISSUE THREAD

**Issue by IceLancerSR** [SteveLeafo/Budford#13]
Standard cemu behavior:
When using gamepad, right mouse click and hold can be used as giro in some games to position stuff (zelda ,project zero etc)
When using Budford Right mouse has no effect at all.

**Comment by SteveLeafo** [comment]
Hi and thanks again for taking the time to raise this issue.

I have finally tracked this one down.  There was an issue where Budford was capturing all mouse events instead of Cemu.

This is fixed in V1.0.73.

Cheers,
SteveLeafo
