### ISSUE TITLE
pro controller buttons not set correct when launching CEMU from budford

### ISSUE THREAD

**Issue by emko** [SteveLeafo/Budford#17]
the gamepad first controller works correct but second player pro controller all ways sets the thumb stick and dpad wrong  but works if a load the Pro profile from the menu.

opening CEMU i get correct controller button assignment 
https://i.gyazo.com/3f33d9fa36926e402c3b31c2e3ca8790.png

launching CEMU from budford i get this
https://i.gyazo.com/36006e0dddcb6daf1c655dae5dbf2dcd.png

i even deleted all the controller profiles and started from scratch and all ways end up with this exact same configuration of the controller with Budford.

https://github.com/SteveLeafo/Budford/commit/58a8456374cad38e5a280a5383cfb807e26d1449
tested 73 and it works as before but v80 has this issue i think its from the changes in that commit

**Comment by SteveLeafo** [comment]
Hmm - can I ask which version of Cemu are you using?

**Comment by emko** [comment]
cemu_1.11.6 , i don't understand why you are trying to change the numbers ? this works perfectly fine but in V80 i think after 10 it skips to 12 and goes to like 27 or something all buttons before 10 don't have any issues 

```
[General]
emulate = Wii U Pro Controller
api = XInput
controller = 1

[Controller]
rumble = 1.000000
leftRange = 1.000000
rightRange = 1.000000
leftDeadzone = 0.250000
rightDeadzone = 0.250000
1 = button_1
2 = button_2
3 = button_4
4 = button_8
5 = button_10
6 = button_20
7 = button_1000000
8 = button_2000000
9 = button_40
10 = button_80
11 = button_4000000
12 = button_4000000
13 = button_8000000
14 = button_10000000
15 = button_20000000
16 = button_100
17 = button_200
18 = button_80000000
19 = button_2000000000
20 = button_1000000000
21 = button_40000000
22 = button_400000000
23 = button_10000000000
24 = button_8000000000
25 = button_200000000
```

**Comment by SteveLeafo** [comment]
Hi, sorry for the late response...

In Cemu 1.11.6, there was a change in the way the controller files were written.  The changes to Budford were added to cater for the case where controller files were copied from previous versions of Cemu, but unfortunately this caused issues in controller files created in Cemu 1.11.6.

V1.0.90 should fix these issues.
