### ISSUE TITLE
Cemuhook's gamepad motion source option is missing

### ISSUE THREAD

**Issue by Bartegu** [SteveLeafo/Budford#18]
In the Cemu 1.12.0 + cemuhook 0.5.6.4 there is an option in gamepad motion source - "Also use for buttons/axes". Setting for this option is missing in Budford V92. This option when not set, seems to default to true `motionSourceIsBtnSource = true` which causes issues in various games. Could you please add setting for this option?

**Comment by SteveLeafo** [comment]
Hi, thanks for letting me know that this was causing issues.

I have added this option to Budford.  It is included in V93 which is now available for download.

Out of curiosity, which games was it causing issues with?

Cheers,
Steve Leafo

**Comment by Bartegu** [comment]
Thanks a lot for quick fix. It was causing issues in Super Smash Bros (problems with main menu) and Super Mario 3D World (camera rotation), possibly other games.
