### ISSUE TITLE
Graphics packs are not displaying in the tab

### ISSUE THREAD

**Issue by HazyHills** [SteveLeafo/Budford#19]
When you right click on a game and select properties, in the graphics packs tab it usually shows a list of all the available packs for the game, it is not doing that

Although the packs are downloaded when Budford starts up, selecting the properties for a game and clicking on the graphics packs tab, nothing appears in there,

**Comment by SteveLeafo** [comment]
Hi, thanks for raising this issue.

I have just uploaded V1.0.102 which should contain a fix. Please let me know if it still isn't working for you.

Sorry I took so long to get around to this, work stuff gets in the way some times...

**Comment by HazyHills** [comment]
That seems to have sorted it :) 

Thanks for the awesome bit of software!
