### ISSUE TITLE
Future Request option to run cemu borderless?

### ISSUE THREAD

**Issue by IceLancerSR** [SteveLeafo/Budford#2]
Future Request option to run cemu borderless?
i am using another app which is not very handy for automated process, because it requires aditional clicks after cemu is started.
Could u add option to run maximized and borderless?
Thanks

**Comment by SteveLeafo** [comment]
I can make it run maximized easily enough, but I am not sure about borderless - which app are you using to to this?

**Comment by IceLancerSR** [comment]
https://www.reddit.com/r/cemu/comments/51ip0b/cemu_borderless_window_mode_application/?st=J3N9AEV8&sh=590463bd

**Comment by IceLancerSR** [comment]
Borderless is working perfectly as soon as cemu finishes loading shaders it goes borderless ! Thank you! It also fixes small white line at top of bar that was present in other tool i was using.

**Although if possible can option be per game and not globally? if that is possible**

**Comment by IceLancerSR** [comment]
Working perfectly per game, amazing job i must say..! 
Thank you!
